### ISSUE TITLE
Bug in MatrixMatrixMult_MT_DDRM.multTransA and concurrent silent failures

### ISSUE THREAD

**Issue by hageldave** [lessthanoptimal/ejml#182]
Hi, first off, love your work.

Now, I wanted to calculate transpose(A)*B with large `DMatrixRMaj` matrices. This would trigger the multithreaded implementation when using `SimpleOperations_DDRM`. However, something goes wrong and an exception is thrown, but it is caught and the stacktrace is printed.

Consider the following code:
```java
import org.ejml.data.DMatrixRMaj;
import org.ejml.dense.row.CommonOps_MT_DDRM;

public class EJMLThings {

	public static void main(String[] args) {
		int n=1_000_000;
		DMatrixRMaj a = new DMatrixRMaj(n, 4);
		DMatrixRMaj b = new DMatrixRMaj(n, 4);
		DMatrixRMaj c = new DMatrixRMaj(a.numCols, b.numCols);

		// now calculate c=trp(a)*b

		/* Theses two lines will result in calling the multi-threaded 
		 * multTransA implementation when matrix 'a' is large
		 * 
		 *   SimpleOperations_DDRM ops = new SimpleOperations_DDRM();
		 *   ops.multTransA(a, b, c);
		 *   
		 * So effectively calling: CommonOps_MT_DDRM.multTransA(a, b, c);
		 */
		CommonOps_MT_DDRM.multTransA(a, b, c);
	}
}
```

As already said, something goes wrong, and I'll put the output of the execution next, **but that is not the point**.
The point is, that the exception is caught internally. [`ConcurrencyOps.loopFor(...)`](https://github.com/lessthanoptimal/ejml/blob/ed7cad3a76057b3000c3a69d65a21be2488bc76b/main/ejml-core/src/pabeles/concurrency/ConcurrencyOps.java#L61) catches `ExecutionException` which is any exception that happens during the submitted task. Then it prints a stacktrace and the exception vanishes into thin air. 
That is a problem, cause I want my application to crash miserably in such a situation and not assume everything works cause I missed the console output. 
Of course, it would be nice if the code was working, but I think there is no unit test for `CommonOps_MT_DDRM`, and it could be that many more methods using `ConcurrencyOps.loopFor(...)` don't work and have slipped unnoticed since they are silenced.
```
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:605)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at pabeles.concurrency.ConcurrencyOps.loopFor(ConcurrencyOps.java:63)
	at org.ejml.dense.row.mult.MatrixMatrixMult_MT_DDRM.multTransA_reorder(MatrixMatrixMult_MT_DDRM.java:146)
	at org.ejml.dense.row.CommonOps_MT_DDRM.multTransA(CommonOps_MT_DDRM.java:100)
	at experiments.EJMLThings.main(EJMLThings.java:23)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2625000 out of bounds for length 16
	at org.ejml.data.DMatrixD1.set(DMatrixD1.java:116)
	at org.ejml.dense.row.mult.MatrixMatrixMult_MT_DDRM.lambda$multTransA_reorder$2(MatrixMatrixMult_MT_DDRM.java:155)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:463)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:620)
	at pabeles.concurrency.ConcurrencyOps.lambda$loopFor$0(ConcurrencyOps.java:63)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by hageldave** [comment]
Alright, so here is my suggestion for dealing with this.

Make the methods that print stacktrace in [`ConcurrencyOps`](https://github.com/lessthanoptimal/ejml/blob/SNAPSHOT/main/ejml-core/src/pabeles/concurrency/ConcurrencyOps.java) instead throw a RuntimeException encapsulating the caught exception. Some of the methods in this class already do this. E.g.:
```java
public static void loopFor( int start, int endExclusive, IntConsumer consumer ) {
   try {
      pool.submit(() -> IntStream.range(start, endExclusive).parallel().forEach(consumer)).get();
   } catch (InterruptedException | ExecutionException e) {
      throw new RuntimeException(e);
   }
}
```

For fixing the multithreaded implementation of `multTransA(a,b,c)` that uses `MatrixMatrixMult_MT_DDRM.multTransA_reorder(a,b,c)`, the bug is here:
https://github.com/lessthanoptimal/ejml/blob/ed7cad3a76057b3000c3a69d65a21be2488bc76b/main/ejml-ddense/src/org/ejml/dense/row/mult/MatrixMatrixMult_DDRM.java#L179
https://github.com/lessthanoptimal/ejml/blob/ed7cad3a76057b3000c3a69d65a21be2488bc76b/main/ejml-ddense/src/org/ejml/dense/row/mult/MatrixMatrixMult_DDRM.java#L180
Your 'macro' or replacement directive on line 179 should iterate to A.numCols instead of A.numRows, just like the regular loop does on the next line.

**Comment by lessthanoptimal** [comment]
Turns out there were more cases of the same bug. https://github.com/lessthanoptimal/ejml/pull/184 That new PR fixes the root cause and adds a test that checks all functions in MatrixMatrixMult_MT_DDRM

**Comment by hageldave** [comment]
Good that these have now surfaced as well and that you could fix them already. Would be great if these fixes went into a new release so I can update my maven dependencies in other projects.

**Comment by lessthanoptimal** [comment]
Sorry about the delay. The plan was to do a faster release with these fixes. This weekend the new release should be on maven central. Just need to merge in another minor fix.

**Comment by lessthanoptimal** [comment]
Released to Maven Central.
