### ISSUE TITLE
Test TestMatrixMatrixMult_MT_DDRM#checkNonSquare fails

### ISSUE THREAD

**Issue by JozsefKutas** [lessthanoptimal/ejml#191]
The test `TestMatrixMatrixMult_MT_DDRM#checkNonSquare` on SNAPSHOT fails when I run the test suite on my laptop. I tried debugging and it seems to be failing on method `multTransA_reorder`.

Output from `./gradlew test`:

```
> Task :main:ejml-ddense:test

TestMatrixMatrixMult_MT_DDRM > checkNonSquare() FAILED
    java.lang.AssertionError: At (3,0) A = 1.9547774139554 B = 1.0 error = 0.9547774139554 tol = 1.0E-8
        at org.ejml.EjmlUnitTests.assertTrue(EjmlUnitTests.java:372)
        at org.ejml.EjmlUnitTests.assertEquals(EjmlUnitTests.java:151)
        at org.ejml.dense.row.mult.TestMatrixMatrixMult_MT_DDRM.checkNonSquare(TestMatrixMatrixMult_MT_DDRM.java:83)

724 tests completed, 1 failed
```

**Comment by JozsefKutas** [comment]
Nevermind, I think this was caused by using outdated generated classes. I reran the autogeneration and everything is now working fine.
