### ISSUE TITLE
Errors in Eigen

### ISSUE THREAD

**Issue by nhavt** [lessthanoptimal/ejml#35]
Hi there,
When computing eigenvalues for the matrix D ( see in attached file) with the EJML v0.34  [D.txt] (https://github.com/lessthanoptimal/ejml/files/2087909/D.txt), I found there is a bug in the function D.svd.getW() as it returned wrong eigenvalues for the matrix D. However when I used the function D.eig().getEigenvalues(), it returned the correct eigenvalues, which are 0.866, and 0.866. Therefore, could you please check this? Thank you in advance!
Nha

**Comment by lessthanoptimal** [comment]
Could you provide a couple of lines of code which demonstrate this problem?

**Comment by nhavt** [comment]
thank you for your response. Here they are

SimpleMatrix D; // read a matrix from the D.txt file
SimpleEVD evd = D.eig();
SimpleSVD svd = D.svd();

System.out.println("evd"+evd.getEigenvalues());
System.out.println("svd"+svd.getW().diag().transpose());

As you can see the last two lines of the code will return different eigenvalues. In principle, both functions should return the correct non-zero eigenvalues, which are  0.866 and -0.866.  Also, I have another problem when computing eigenvalues for the M matrix (see in attached file) [M.txt](https://github.com/lessthanoptimal/ejml/files/2089087/M.txt). For example, if I use the following codes: 
SimpleMatrix M;  // read a matrix from the M.txt file
SimpleEVD evd = M.eig(), it returned the error messages: 
Eigenvalue Decomposition failed
	at org.ejml.simple.SimpleEVD.<init>(SimpleEVD.java:57)
	at org.ejml.simple.SimpleBase.eig(SimpleBase.java:950)

Could you please have a look at it? Thank you in advance!

**Comment by lessthanoptimal** [comment]
I've verified that this is a real issue. I was able to decompose the M.txt matrix by increasing the number of exceptional shifts, but I'm wondering if there might be a better way to perform this iteration. Eigenvalue decomposition is very tricky to get right.

I'll look into the SVD issue a little bit later

**Comment by lessthanoptimal** [comment]
@nhavt  If possible can you figure out a simple formula to generate matrices which cause the current algorithm to fail? That will make creating a unit test much easier.

**Comment by nhavt** [comment]
Thank you for your help. As to a simple formula to generate matrices, I don't have a simple formula at the moment. Looking at the structure of M matrix, I observe there are a lot of zeros in this matrix. So, my guess is that if you could create a sparse matrix with a few non-zero elements. That might give you a unit test. However, I will double check it and let you know. Thank you!
