### ISSUE TITLE
Using serialization with SimpleMatrix generates NPE in 0.38

### ISSUE THREAD

**Issue by AngledLuffa** [lessthanoptimal/ejml#59]
I have some models which are stored by serializing a bunch of SimpleMatrix objects representing the model state.  This worked fine in 0.23, and after years of just using the old version, we decided to upgrade to the latest version, 0.38.  This does not work because SimpleMatrix operations such as mult() do not work on vectors which have been deserialized.  Here is a fairly short example which demonstrates the problem:

```
import java.io.*;

import org.ejml.simple.SimpleMatrix;

public class foo {
  public static void main(String[] args) throws IOException, ClassNotFoundException {
    SimpleMatrix foo = new SimpleMatrix(1, 2);
    foo.set(0, 0, 3.0);

    SimpleMatrix bar = new SimpleMatrix(2, 1);
    bar.set(0, 0, 3.0);

    System.out.println(foo.mult(bar));

    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    ObjectOutputStream oos = new ObjectOutputStream(baos);

    oos.writeObject(foo);
    oos.writeObject(bar);
    oos.close();

    ByteArrayInputStream bais = new ByteArrayInputStream(baos.toByteArray());
    ObjectInputStream ois = new ObjectInputStream(bais);

    foo = (SimpleMatrix) ois.readObject();
    bar = (SimpleMatrix) ois.readObject();

    System.out.println(foo.mult(bar));
  }
}
```

Result:

```
Type = DDRM , rows = 1 , cols = 1
 9.0000E+00

Exception in thread "main" java.lang.NullPointerException
        at org.ejml.simple.SimpleBase.mult(SimpleBase.java:162)
        at foo.main(foo.java:28)
```

Expected result: it should print 9.0 twice

As far as I can tell, the reason is there is a transient variable 

```
    protected transient AutomaticSimpleMatrixConvert convertType = new AutomaticSimpleMatrixConvert();
```

This does not get created when you deserialize a SimpleMatrix and use it directly.

**Comment by lessthanoptimal** [comment]
thanks. this should be easy to fix

**Comment by lessthanoptimal** [comment]
Fixed in latest SNAPSHOT. Thanks for the bug report!
