### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by mattbru2** [lessthanoptimal/ejml#8]
I am trying to build but getting the following error.  Any ideas?

Caused by: org.gradle.api.UncheckedIOException: java.util.zip.ZipException: The JAR/ZIP file (C:\workspace\zz_sources\ejml-v0.28-src\main\dense64\build\libs\dense64-0.28.jar) seems corr
upted, error: error in opening zip file
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest.getEffectiveManifest(DefaultOsgiManifest.java:86)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest_Decorated.getEffectiveManifest(Unknown Source)
        at org.gradle.api.java.archives.internal.DefaultManifest.writeTo(DefaultManifest.java:151)
        at org.gradle.api.java.archives.internal.DefaultManifest.writeTo(DefaultManifest.java:35)
        at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:64)
        at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:58)
        at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.copyTo(MapFileTree.java:208)
        at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.getFile(MapFileTree.java:164)
        at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.getLastModified(MapFileTree.java:199)
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.getLastModified(DefaultFileCopyDetails.java:71)
        at org.gradle.api.internal.file.archive.ZipCopyAction$StreamAction.visitFile(ZipCopyAction.java:99)
        ... 93 more
Caused by: java.util.zip.ZipException: The JAR/ZIP file (C:\workspace\zz_sources\ejml-v0.28-src\main\dense64\build\libs\dense64-0.28.jar) seems corrupted, error: error in opening zip fi
le
        at aQute.bnd.osgi.ZipResource.build(ZipResource.java:57)
        at aQute.bnd.osgi.ZipResource.build(ZipResource.java:35)
        at aQute.bnd.osgi.Jar.<init>(Jar.java:56)
        at aQute.bnd.osgi.Jar.<init>(Jar.java:76)
        at aQute.bnd.osgi.Analyzer.setClasspath(Analyzer.java:1245)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest.setAnalyzerProperties(DefaultOsgiManifest.java:127)
        at org.gradle.api.internal.plugins.osgi.DefaultOsgiManifest.getEffectiveManifest(DefaultOsgiManifest.java:69)
        ... 103 more

**Comment by lessthanoptimal** [comment]
Not sure.  What architecture are you trying to build it on and can you paste the exact command (or IDE) you use to build it?

**Comment by mattbru2** [comment]
I was trying to compile on Windows.  I ended up just switching to Linux.

C:\workspace\zz_sources\ejml-v0.28-src>gradle oneJarBin
:main:core:compileJava UP-TO-DATE
:main:core:processResources UP-TO-DATE
:main:core:classes UP-TO-DATE
:main:core:jar UP-TO-DATE
:main:dense64:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:main:dense64:processResources UP-TO-DATE
:main:dense64:classes
:main:denseC64:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:main:denseC64:processResources UP-TO-DATE
:main:denseC64:classes
:main:dense64:jar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:dense64:jar'.
> Could not add MANIFEST.MF to ZIP 'C:\workspace\zz_sources\ejml-v0.28-src\main\dense64\build\libs\dense64-0.28.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.474 secs

**Comment by lessthanoptimal** [comment]
Yeah I have no idea why that's broken.  There is nothing special going on.
Kinda wonder if it might be a Gradle bug.  Maybe updating the version of
gradle will fix it?

On Thu, Jan 14, 2016 at 12:42 PM, mattbru2 <notifications@github.com> wrote:

> I was trying to compile on Windows. I ended up just switching to Linux.
>
> C:\workspace\zz_sources\ejml-v0.28-src>gradle oneJarBin
> :main:core:compileJava UP-TO-DATE
> :main:core:processResources UP-TO-DATE
> :main:core:classes UP-TO-DATE
> :main:core:jar UP-TO-DATE
> :main:dense64:compileJava
> warning: [options] bootstrap class path not set in conjunction with
> -source 1.6
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 warning
> :main:dense64:processResources UP-TO-DATE
> :main:dense64:classes
> :main:denseC64:compileJava
> warning: [options] bootstrap class path not set in conjunction with
> -source 1.6
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 warning
> :main:denseC64:processResources UP-TO-DATE
> :main:denseC64:classes
> :main:dense64:jar FAILED
>
> FAILURE: Build failed with an exception.
>
>    -
>
>    What went wrong:
>    Execution failed for task ':main:dense64:jar'.
>
>    Could not add MANIFEST.MF to ZIP
>    'C:\workspace\zz_sources\ejml-v0.28-src\main\dense64\build\libs\dense64-0.28.jar'.
>
>    -
>
>    Try:
>    Run with --stacktrace option to get the stack trace. Run with --info
>    or --debug option to get more log output.
>
> BUILD FAILED
>
> Total time: 17.474 secs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lessthanoptimal/ejml/issues/8#issuecomment-171773658>.
>



-- 
"Now, now my good man, this is no time for making enemies."    — Voltaire
(1694-1778), on his deathbed in response to a priest asking that he
renounce Satan.

**Comment by lessthanoptimal** [comment]
Closing issue due to lack of activity.
