### ISSUE TITLE
UtilEjml not found

### ISSUE THREAD

**Issue by atoota** [lessthanoptimal/ejml#86]
Hello,

I'm experiencing a weird behaviour. I used to use ejml dense matrixes for a long time with the 0.26 version.
I recently tried to migrate to the 0.39 version, everything is working well on our development computers (windows 10) and our integration servers (Ubuntu 20.04), but as soon as I deploy our application on our production servers (Ubuntu 20.04, openjdk 11.0.8), I have the following error when I try to create a DMatrixRMaj : 

 java.lang.NoSuchMethodError: 'void org.ejml.UtilEjml.checkTooLarge(int, int)'
                at org.ejml.data.DMatrixRMaj.<init>(DMatrixRMaj.java:120)
                at com.sofresud.naval.server.fusion.sensor.BasicSensorModel.<init>(BasicSensorModel.java:13)
                at com.sofresud.naval.server.fusion.TrackFusion.setConf(TrackFusion.java:361)
                at com.sofresud.naval.vms.server.listener.ApplicationServletContextListener.contextInitialized(ApplicationServletContextListener.java:456)
...

Here is what we declared in the pom.xml : 
<dependency>
       <groupId>org.ejml</groupId>
       <artifactId>ejml-ddense</artifactId>
       <version>0.39</version>
</dependency>

In our app libraries directory, the dependancies are correctly deployed (ejml-core-0.39.jar and ejml-ddense-0.39.jar), and as UtilEjml in contained in ejml-core, it should be available.

I tried to directly call UtilEjml in my startup class :  
UtilEjml.checkTooLarge(2, 2);

and now I have the following error : 

 java.lang.NoSuchMethodError: 'void org.ejml.UtilEjml.checkTooLarge(int, int)'
                at com.sofresud.naval.vms.server.listener.ApplicationServletContextListener.contextInitialized(ApplicationServletContextListener.java:443)
                at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4685)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
...

I don't understand why I can't access to this class, am I missing a dependancy ? And why I have this issue only on a particular platform?

**Comment by lessthanoptimal** [comment]
UtilEjml is defined in `ejml-core` which `ejml-ddense` depends on. Your build script should have automatically added it. It does look like a missing dependency.

**Comment by lessthanoptimal** [comment]
Closing. Assuming this was a build configuration issue.
